services:
  app:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    container_name: yii_app
    restart: unless-stopped
    ports:
      - "8375:80"
      - "9001:9001"
    volumes:
      - ../basic:/var/www/html
      - ./php-apache/vhost.config:/etc/apache2/sites-available/000-default.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/web
      XDEBUG_MODE: debug,develop # enable debug and develop features
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003" # Xdebug to connect to your IDE on port 9003
    depends_on:
      - db
    networks:
      - yii2

  db:
    image: mysql:8.0
    container_name: yii_db
    restart: unless-stopped
    ports:
      - "3606:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii
      MYSQL_USER: yii
      MYSQL_PASSWORD: yii
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - yii2

networks:
  yii2:

volumes:
  db_data: